#!/usr/bin/python

import urllib.request
import json
import datetime


def convert_time(time, convert_from, convert_to):
    return datetime.datetime.strptime(time, convert_from).time().strftime(convert_to)

url = 'https://ipinfo.io/loc'
with urllib.request.urlopen(url) as response:
    ip = response.read().decode('utf-8')

ip = ip.split("\n")[0].split(",")

url = f'http://api.aladhan.com/timings?latitude={ip[0]}&longitude={ip[1]}&school=1&method=99&methodSettings=18,null,15'
with urllib.request.urlopen(url) as response:
    html = response.read()

convert_from = "%H:%M"
wanted_time_format = "%I:%M %p"
timings = json.loads(html)['data']['timings']
del timings['Sunset']
del timings['Imsak']
del timings['Midnight']
current_time = datetime.datetime.now().time()

for name, time in timings.items():
    datetimed = datetime.datetime.strptime(timings[name], convert_from).time()

    # if current_time >= datetimed:
    #     current_prayer = [name, convert_time(
    #         time, convert_from, wanted_time_format)]
    # else:
    #     current_prayer = ['Isha', 'Anytime']

    if current_time <= datetimed:
        next_prayer = [name, convert_time(
            time, convert_from, wanted_time_format)]
        break

day = json.loads(html)["data"]["date"]["hijri"]

print(f'{day["weekday"]["en"]} {day["day"]} {day["month"]["en"]}, {day["year"]} {next_prayer[0]} {next_prayer[1]}')
